### ISSUE TITLE
MTMC Tracking Pipeline 

### ISSUE THREAD

**Issue by ming1993li** [KevinQian97/ELECTRICITY-MTMC#1]
Could you please give an instruction about the whole pipeline? What you have provided is actually the method of ReID.

**Comment by KevinQian97** [comment]
Hi! 
You can run the whole system through "bash test.sh" for inference. We only provide the training code for ReID module in that it is the only part that we re-trained on AI city challenge data sets.  For the whole pipeline, I think u can resort to our paper.

**Comment by limingatunc** [comment]
Hi, 

Thank you for your answer. You mean you just trained ReID model on the official dataset of Track3. And the models for vehicle detection and MOT tracking were not trained on official dataset of Track3 and they just used trained weights from other papers. Is that right?

**Comment by ming1993li** [comment]
Hi,

Thank you for your answer. You mean you just trained ReID model on the official dataset of Track3. And the models for vehicle detection and MOT tracking were not trained on official dataset of Track3 and you just used trained weights from other papers. Is that right?

**Comment by KevinQian97** [comment]
Yes，we just re-trained the ReID module on Track3 data set. For detection module we directly used the one pretrained on COCO.

**Comment by KevinQian97** [comment]
close it since the issue already solved.
