### ISSUE TITLE
Evaluation code?

### ISSUE THREAD

**Issue by dengxyking** [KevinQian97/ELECTRICITY-MTMC#14]
Thank you for your sharing. When I try to reproduce your result, I find two problems .
There seems to be no evaluation code, i.e. score of 0.4585 as described in the paper.

**Comment by KevinQian97** [comment]
Hi Deng!
Thanks for your interest. You can submit the output to the official evaluation site:
https://www.aicitychallenge.org/2020-ai-city-challenge/

**Comment by dengxyking** [comment]
Thank you, Kevin.Output refers to the generated track3. txt?

**Comment by imranzaman5202** [comment]
> Thank you, Kevin.Output refers to the generated track3. txt?

Yes upload this file on https://www.aicitychallenge.org/2020-ai-city-challenge/

**Comment by KevinQian97** [comment]
Yes
