### ISSUE TITLE
about the track3.txt

### ISSUE THREAD

**Issue by jiyidefeng1990** [KevinQian97/ELECTRICITY-MTMC#2]
Thank you for opening up such a great project. Could you give me some instructions on how to get the vehicle that appeared in different cameras from the final results "track3.txt"? In other words, how to get the results of Figure 10 in your paper from "track3.txt"?

**Comment by KevinQian97** [comment]
The same vehicle shares the same tracklet id.

**Comment by jiyidefeng1990** [comment]
Do you mean that in track3.txt, even if the camera ID is different, as long as the track ID is the same, it is the same car?
How can I find the car picture? Can I find the car picture in image_query through track id?

**Comment by KevinQian97** [comment]
For the first question, yes, that's the requirement of track 3 in AI city. For the second question, I thought u can crop it by yourself.

**Comment by jiyidefeng1990** [comment]
I see, thank you very much!

**Comment by jiyidefeng1990** [comment]
Sorry to disturb you again, another question is, why are there many duplicate items in track3.txt? For example, the items in camera44 have occured 4 or 5 times in different parts of track3.txt, do the different positions in the document have any special meaning?

**Comment by KevinQian97** [comment]
Hi, if the tracking id is also the same then I don't think it has special meanings. Given it won't influence the official metric of Track3, I guess there are no special parsing codes to tackle the redundancy.

**Comment by jiyidefeng1990** [comment]
When I took pictures of cars from the corresponding videos according to track3.txt, I found that even though some vehicles shared same track id, from the naked eyes,these vehicles have a great difference in appearance, even the color is not the same, thus I think these pictures should not belong to the same car.
  It seems that the current project has a good effect on vehicle tracking in a single camera, but the matching of multiple cameras to the same vehicle is not ideal. Did you observe the same result, or did I make some mistakes in my own processing?

**Comment by KevinQian97** [comment]
According to our experience, the visualization of the validation set seems not bad. I think it challenging to make it perfect considering all the scenes in the test set are hidden scenes and that's why the final performance is 0.46. Maybe we will continue improving it in next year's competition. Will be grateful if u can give us some suggestions.

**Comment by jiyidefeng1990** [comment]
Thank you for your help
