### ISSUE TITLE
DataLoader worker exited unexpectedly

### ISSUE THREAD

**Issue by HanwenCao** [KevinQian97/ELECTRICITY-MTMC#4]
Hi! 
When running `./identifier/test.py`, I got an error said `RuntimeError: DataLoader worker (pid(s) 2685) exited unexpectedly`. 
The error happens at `for batch_idx, (imgs, pids, camids, _) in enumerate(galleryloader):`, and everything is fine for queryloader.
I tried to make `numworkers=4` smaller, like `numworkers=2`, but still got the error. Then I set it to 0. But it made the loader extremely slow so that no one knows if it can work or not.

Would you have any suggestions? Thank you!

**Comment by quanghuy0497** [comment]
Hi, how did you resolve that problem?
