### ISSUE TITLE
while running test.sh, syntax error on '*' usage

### ISSUE THREAD

**Issue by yifenghuang** [KevinQian97/ELECTRICITY-MTMC#8]
Hi I try to test the code and meet some problems.

while I running test.sh, it's say"packed_tensor = torch.zeros((rounded_size, *tensor.shape[1:]),
                                dtype=tensor.dtype, device=tensor.device)" in ./util/tensor.py
has a syntax error (line 7). 

env:python2.7+torch1.5

I also tested it under python3.7 enviroment and it's can't import module "detectron2"

thank you.

**Comment by quanghuy0497** [comment]
@yifenghuang Hi, how did you resolve this problem?
